### ISSUE TITLE
Cannot spin the wheel

### ISSUE THREAD

**Issue by WEEZOOKARP** [dojwun/doj-casino#10]
When I try to interact with the wheel nothing happens I have all the stated dependencies
textui
casinoui

You did mention something about peeking or smth like that but you never put a resource name or link to said resource that allows you to peek
https://cdn.discordapp.com/attachments/446201646687584257/914122638115364864/unknown.png

**Comment by WEEZOOKARP** [comment]
thought that it may be qb-target but nope

**Comment by dojwun** [comment]
yeah you need to spin the wheel with qb-target

**Comment by dojwun** [comment]
you can find the export code in  casino-walls/client/casino-addons.lua , but i will have an option to press e or peek

**Comment by WEEZOOKARP** [comment]
![image](https://user-images.githubusercontent.com/76672483/143974799-39560572-a26c-4b4b-916f-aa712170120f.png)
not so sure of qb-target working properly with this

**Comment by WEEZOOKARP** [comment]
but e works now so pog

**Comment by dojwun** [comment]
ive added an option to peek or press
