### ISSUE TITLE
bro. hellacious effort

### ISSUE THREAD

**Issue by kingofkingzcd** [dojwun/doj-casino#13]
Great effort unfortunately NONE of it works at all. it will just say you dont have any chips even if you have millions. hope its still maintained and fixed soon.

**Comment by dojwun** [comment]
not sure how, all my item checks work fine for me.. i wouldnt keep it up if it was this broken

**Comment by dojwun** [comment]
["casino_redchip"] 				 = {["name"] = "casino_redchip", 			 ["label"] = "Casino Chip", 			["weight"] = 0, 		["type"] = "item", 		["image"] = "casino_redchip.png", 				["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false,   ["combinable"] = nil,   ["description"] = "Diamond Casino Inside Track Chip"}, 
	["casino_whitechip"] 			 = {["name"] = "casino_whitechip", 			 ["label"] = "Casino Chip", 			["weight"] = 0, 		["type"] = "item", 		["image"] = "casino_whitechip.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false,   ["combinable"] = nil,   ["description"] = "Diamond Casino Slot Machine Chip"},
	["casino_bluechip"] 			 = {["name"] = "casino_bluechip", 			 ["label"] = "Casino Chip", 			["weight"] = 0, 		["type"] = "item", 		["image"] = "casino_bluechip.png", 				["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false,   ["combinable"] = nil,   ["description"] = "Diamond Casino Roulette Chip"},
	["casino_blackchip"] 			 = {["name"] = "casino_blackchip", 			 ["label"] = "Casino Chip", 			["weight"] = 0, 		["type"] = "item", 		["image"] = "casino_blackchip.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false,   ["combinable"] = nil,   ["description"] = "Diamond Casino Blackjack Chip"},
	["casino_goldchip"] 			 = {["name"] = "casino_goldchip", 			 ["label"] = "Casino Chip", 			["weight"] = 0, 		["type"] = "item", 		["image"] = "casino_goldchip.png", 				["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false,   ["combinable"] = nil,   ["description"] = "Diamond Casino Chip"},
	["casino_member"] 				 = {["name"] = "casino_member", 			 ["label"] = "Casino Membership", 		["weight"] = 500, 		["type"] = "item", 		["image"] = "casino_member.png", 				["unique"] = true, 		["useable"] = false, 	["shouldClose"] = false,   ["combinable"] = nil,   ["description"] = "Diamond Casino Member Card"},
	["casino_vip"] 					 = {["name"] = "casino_vip", 			 	 ["label"] = "V.I.P Membership", 		["weight"] = 500, 		["type"] = "item", 		["image"] = "casino_vip.png", 				    ["unique"] = true, 		["useable"] = false, 	["shouldClose"] = false,   ["combinable"] = nil,   ["description"] = "Diamond Casino V.I.P Card"},

**Comment by kingofkingzcd** [comment]
i figured it out. somehow i was missing a file from unzipping. idk. only issue i have now is roulette. doesnt really like to let you bet and do the tables spawn auto or do i need to set coords to existing roulette tables?

**Comment by kingofkingzcd** [comment]
i need those slots but damn i dont have 75 bucks to spend. im already wayyy deep in fivem. lol

**Comment by dojwun** [comment]
you have to add tables yourself, not like the blackjack script where it uses the already existing tables

**Comment by dojwun** [comment]
message me on discord 

> i need those slots but damn i dont have 75 bucks to spend. im already wayyy deep in fivem. lol

message me on discord </dojwun>#2103

**Comment by dojwun** [comment]
``` </dojwun>#2103 ```

**Comment by kingofkingzcd** [comment]
sent you a request.
