### ISSUE TITLE
2 issues im having right now

### ISSUE THREAD

**Issue by tom091291** [dojwun/doj-casino#14]
so 1 issue im having for blackjack and roulette is an error 

No such export HideCasinoUi in resource casinoUi

and when i sit down at the blackjack table it bugs and i have to relog. then crashes me if i go back to my last location,

**Comment by dojwun** [comment]
"No such export HideCasinoUi in resource casinoUi"- do you have the casinoUi script

"and when i sit down at the blackjack table it bugs and i have to relog. then crashes me if i go back to my last location"- what do you man by "bugs" , if you are able to send a video

**Comment by tom091291** [comment]
where would i get the casino Ui script from, also when i sit down at the table it then bugs but i think its because i dont have the casinoUi script in, could you link me to it and also maybe add it in so others can have the link directly to it. thanks in advance

**Comment by dojwun** [comment]
be sure to read the read me,it was in there

**Comment by dojwun** [comment]
https://github.com/dojwun/casinoUi
