### ISSUE TITLE
Casino Chips don't stack. KVG Blackjack

### ISSUE THREAD

**Issue by gigitygamer** [dojwun/doj-casino#29]
When I win the chips do not stack, and it winn only pull from winnings saying I don't have enough chips.. Only changes I made was all the calls to "Casino_Goldchips" to casino_chips

**Comment by Andyauk** [comment]
> When I win the chips do not stack, and it winn only pull from winnings saying I don't have enough chips.. Only changes I made was all the calls to "Casino_Goldchips" to casino_chips

I've found that, its always been a thing, but you can manually stack them,.
