### ISSUE TITLE
CIPHER. 

### ISSUE THREAD

**Issue by N0str4** [dojwun/doj-casino#30]
The resource "casino-poker" has been found to contain code that has been flagged as malicious and has been disabled for the continued security and stability of your server
The resource has been found to contain cipher-panel and similar malware

cipher-panel is a malicious trojan commonly contained in leaked resources, this allows anyone to access, browse, edit and control your server remotely, as such it poses a huge security risk to your server.

Not good... it's really not good.

**Comment by dojwun** [comment]
wait wtf ima remove this immediately

**Comment by dojwun** [comment]
not my intention apologies

**Comment by dojwun** [comment]
i was looking through the code and im pretty sure i had the part commented out in the sv_main.lua line 339 it was never active when i posted it

**Comment by Andyauk** [comment]
> 

you just needed to remove the commented out bit, as it can be picked up still.  and rend a warning.
it happens if you have a leeked script, and it bleeds over to other scripts. 

as i like my poker hehe
