### ISSUE TITLE
Casino Chips

### ISSUE THREAD

**Issue by DayRK** [dojwun/doj-casino#31]
Is it possible for this casino script to use casinochips (money type) than casinochips as item?

**Comment by bellae4f** [comment]
Casino chips are the tangible currency of excitement and possibility within the vibrant world of gambling. These colorful tokens, each with their unique designs and denominations, represent the essence of the casino https://casinohex.sk/online-kasina/5gringos/ experience. From the weight of the chips in hand to the satisfying clink as they hit the felt table, they evoke a sense of anticipation and thrill. Beyond their practical use in wagering, casino chips hold sentimental value, serving as mementos of memorable wins and losses. Whether stacked high in victory or scattered in defeat, casino chips are emblematic of the exhilarating journey that unfolds within the walls of the casino.
