### ISSUE TITLE
Adding More Casino Chips Question

### ISSUE THREAD

**Issue by rxnm** [dojwun/doj-casino#34]
Hey, loving the script mate, good job! After some testing though I have come across a couple of problems which I shall post.

So the first one is (Luckywheel) I added my own chips so now I have gold, black, blue, red, and white chips. But the question is how I have added it is not a good way I think I basically copied the ServerEvent **(casino-walls\server\casino.lua)** and duplicated it for each chip like so:

`RegisterServerEvent("qb-casino:server:BlackSell")
AddEventHandler("qb-casino:server:BlackSell", function()
    local src = source
    local price = Config.casinoChipPrice
    local Player = QBCore.Functions.GetPlayer(src)
    local xItem = Player.Functions.GetItemByName("casino_blackchip")
    if xItem ~= nil then
        local quantity = 0
        for k, v in pairs(Player.PlayerData.items) do 
            if Player.PlayerData.items[k] ~= nil then 
                if ItemList[Player.PlayerData.items[k].name] ~= nil then 
                    quantity = quantity + Player.PlayerData.items[k].amount
                    Player.Functions.RemoveItem(Player.PlayerData.items[k].name, Player.PlayerData.items[k].amount, k)
                end
            end
        end
        price = price * quantity
        Player.Functions.AddMoney(Config.payment, price, "sold-casino-chips")
        TriggerClientEvent('inventory:client:ItemBox', source, QBCore.Shared.Items['casino_blackchip'], "remove", quantity)
        TriggerClientEvent('QBCore:Notify', src, "You sold "..quantity.." Black chips for $"..price)
        TriggerEvent('qb-log:server:CreateLog', 'guedesteste', 'Dinheiro Venda | '..Player.PlayerData.name, 'default', quantity.." fichas de ouro por "..price.."€")
        TriggerClientEvent("doj:casinoChipMenu", src)
		quantity = 0
    else
        TriggerClientEvent('QBCore:Notify', src, "You dont have any casino chips...", "error") 
        TriggerClientEvent("doj:casinoChipMenu", src)
    end
end)`

The whole fils is attached, I just want to know if there is a better way instead of the way I have done. It does work! only problem with it is when you win ships it says **(Congratulations! You won xxxx casino_colchip!)** - (xxxx being the number and col being the color of said chip).
[casino.txt](https://github.com/dojwun/doj-casino/files/12287095/casino.txt)

**Comment by dojwun** [comment]
qb-core has been removed, try using qbx/ ox inventory
