### ISSUE TITLE
Invalid vector field: sound

### ISSUE THREAD

**Issue by rxnm** [dojwun/doj-casino#35]
Okay, another problem is on the luckywheel when you win the 50.000k prize, it is meant to give you the 50k plus play the cash sound, but it doesn't, it gives you nothing, and splashes out this error: 

![Screenshot_2](https://github.com/dojwun/doj-casino/assets/2183651/b628b22e-a60e-478a-b89d-aed9bf919c9d)

I tried everything, the sound is right just like on every other cash prize, I lowered the cash amount, the chance, everything, and still the same error. Also, you have to restart the casino-luckywheel after the error as it locks up the wheel and just takes your money but does nothing. 

Lines 185, **186**, and 187:
`if s == GetPlayerServerId(PlayerId()) then
		if p.sound == 'car' then
			PlaySoundFromEntity(-1, "Win_Car", _wheel, 'dlc_vw_casino_lucky_wheel_sounds', 1, 1)`

doesn't make sense the error being on line 186 which is car and for me the sound is on the default cash.

**Comment by RabbithNL** [comment]
i have the same problem does any1 has a solution?
