### ISSUE TITLE
Winning the car error (vehicleData)

### ISSUE THREAD

**Issue by rxnm** [dojwun/doj-casino#36]
Okay, last issue to report, lol. When you win the car it all works fine, BUT when you open the qb-phone it splashes up this error, I think connected to the garage app possibly?!

![Screenshot_3](https://github.com/dojwun/doj-casino/assets/2183651/fb0f3118-86c4-4bef-bc69-a41194bb4482)

**Comment by dojwun** [comment]
qb-core is removed, maby new car works with qbx
