### ISSUE TITLE
casino-poker error

### ISSUE THREAD

**Issue by Maarz666** [dojwun/doj-casino#39]
SCRIPT ERROR: Execution of native fb71170b7e76acba in script host failed: Error executing native 0xfb71170b7e76acba at address FiveM_b2802_GTAProcess.exe+362BE13

**Comment by Maarz666** [comment]
https://github.com/dojwun/doj-casino/assets/65540476/46548439-7802-40b6-b87c-4e326ab12db8

**Comment by dojwun** [comment]
try new casino pack
