### ISSUE TITLE
Door collision

### ISSUE THREAD

**Issue by dpshadowz420** [dojwun/doj-casino#44]
There seems to be another set of doors on the outside of the casino, making it so you can't see inside.. how do you fix this?

**Comment by dpshadowz420** [comment]
![image](https://github.com/dojwun/doj-casino/assets/154547294/6039a98b-b162-47f4-bdfe-2a6607f9d5bc)
![image](https://github.com/dojwun/doj-casino/assets/154547294/6c2312fb-23a7-4ecc-adc2-0a8f4573b539)
![image](https://github.com/dojwun/doj-casino/assets/154547294/13a9f6ab-40d5-4052-9534-bbcbf57334ae)

**Comment by RabbithNL** [comment]
any fix yet?

**Comment by mwuhahaa** [comment]
GO to bob74 ipl and disable casino dlc

**Comment by mwuhahaa** [comment]
> any fix yet?

GO to bob74 ipl and disable casino dlc
