### ISSUE TITLE
casino-slots (reliable network event overflow)

### ISSUE THREAD

**Issue by rapeurtueur** [dojwun/doj-casino#45]
Disconnect ater few secondes sitting behind the slots machines.

If I do in the console "toggle neteventlog"

As soon as I sit down at a slot machine, it starts spamming in the console.

After a few seconds I disconnected with the error "Reliable network event overflow"

This is because of a wait(0) on line 277 of client.lua

If I modify the value it spams less quickly but we are always disconnected after a few seconds and if I increase it too much the slots machine is no longer usable

![image](https://github.com/dojwun/doj-casino/assets/2059913/8a252374-5bf2-4592-ad17-21d877a84489)
![image](https://github.com/dojwun/doj-casino/assets/2059913/b983ca49-b4a1-45c7-9211-248cfda8d250)

**Comment by rapeurtueur** [comment]
He don't stop calling this trigger 
QBCore.Functions.TriggerCallback('doj:server:CasinoChipsAmount', function(result)
at line 198 from the client.lua (casino-slots)

**Comment by dojwun** [comment]
ive remove old hacky way of getting chips after years... new casino updated with qbx/ox
