### ISSUE TITLE
Does this work for QB Core?

### ISSUE THREAD

**Issue by Nasalord** [dojwun/doj-casino#48]
Im having issues with this script on my qbcore server if anyone can help me would be appreciated.

**Comment by Flameslinger02** [comment]
same here. I assume it probably just Doesn't work with QBCore.

**Comment by Flameslinger02** [comment]
@Nasalord I got it working
you have to trim the script names down to casino and casinoui then add [ ] around the casino folder because it is a list of folders, reflect this in your server config with the ensure lines.

and be sure to add the pictures to your qb-inventory --> html --> images

**Comment by dojwun** [comment]
ive removed most qbcore, its recommended to use [qbx](https://github.com/Qbox-project)
