### ISSUE TITLE
Numbers from 1 to 9 do not give a prize

### ISSUE THREAD

**Issue by lush0n3** [dojwun/doj-casino#52]
https://github.com/dojwun/doj-casino/blob/a9ad431f0658fc649be6b8cefe8d84b5ee64d61b/casino-roulette/server/sv_main.lua#L197

The condition of line 197 will only be positive if the numbers are from 10 to 36, the numbers from 9 to 1 are not recognized and therefore are false, this causes the prize not to be delivered to the winner.

Solution: *(Replace the condition with this)*
`(elseif betData.betId >= '1' or betData.betId <= '36') and (WinningBetIndex == betData.betId then)`

Thank you for your attention, I hope it can solve others' problems!

**Comment by dojwun** [comment]
okay thank you should be updated
