### ISSUE TITLE
Qbcore version

### ISSUE THREAD

**Issue by Deazy17** [dojwun/doj-casino#53]
Hello can you release qbcore version please?

**Comment by dojwun** [comment]
i dont use qbcore anymore, its been recommended to update to qbx, hence the update.
Here is a link to an older version of casino with qbcore
https://github.com/dojwun/doj-casino/tree/92a5d5e76f1c6c900ae41d61872fec5d10696d86

**Comment by 0411447** [comment]
Do you happen to have a copy of the old casinoUI

**Comment by 0411447** [comment]
qb version I mean

**Comment by dojwun** [comment]
just rename casino-ui to casinoUI
