### ISSUE TITLE
Winning in blackjack is bugged

### ISSUE THREAD

**Issue by DannysRP** [dojwun/doj-casino#6]
The payout for black jack does not work. When it comes to paying out it sends an error for a native 
![image](https://user-images.githubusercontent.com/88177315/141701863-058c94d0-283e-4fe3-bb72-8add4f2ef756.png)

**Comment by Howsn** [comment]
I cant see the npc for Casino Shop and Horse Bets after update. :)

**Comment by dojwun** [comment]
> The payout for black jack does not work. When it comes to paying out it sends an error for a native ![image](https://user-images.githubusercontent.com/88177315/141701863-058c94d0-283e-4fe3-bb72-8add4f2ef756.png)

okay it should now be fixed

**Comment by dojwun** [comment]
> I cant see the npc for Casino Shop and Horse Bets after update. :)

okay i re-added them
