### ISSUE TITLE
Black with multiple people

### ISSUE THREAD

**Issue by DannysRP** [dojwun/doj-casino#7]
Black Jack seems to be bugged with multiple people. If a few people get on a table at one time the people cannot see the UI to place a bet. Only one person can see the UI and place a bet. You then have to wait for them to finish the game to be able to see the UI. Also you will spam between the seats randomly while playing. When the game is finished it also takes the ped like 20 seconds to pull a persons cards 
![image](https://user-images.githubusercontent.com/88177315/141711359-c3ca5b70-0317-4d86-8deb-880e90a80488.png)

**Comment by dojwun** [comment]
alright, sounds like it needs a re-work i work on that soon

**Comment by DannysRP** [comment]
I can send video clips if need be as well. It is very strange. You it works just fine if you play by yourself. Execept for the switching between seats randomly. It does that when playing with others as well. You may end up sitting inside another player

**Comment by dojwun** [comment]
yea a video would help alot, and ive only tested it solo but never experienced the seat switching

**Comment by dojwun** [comment]
i will also work on a full re-wright

**Comment by dojwun** [comment]
ive combed through the code and i cant find the reason for seat swapping etc.. there must be some reason for it so i will continue looking

**Comment by dojwun** [comment]
just noticed this was the wrong bug, apologies, this still might be bugged i have no way to test properly

**Comment by V3N00M** [comment]
I believe it still is, I can confirm the random seat swapping

**Comment by V3N00M** [comment]
This is still happening, please click here for an example. https://youtu.be/wFzXX4o_-3Y

**Comment by dojwun** [comment]
awesome man thank you for this, i can try to identify the problem now

**Comment by dojwun** [comment]
a new blackjack has been added, this one i will still try to find a fix

**Comment by V3N00M** [comment]
@dojwun I played the qb-blackjack last night with a friend and it seemed to work fine now? I also tried the new casino-blackjack, it needs some work still

**Comment by dojwun** [comment]
really? nice man i pushed a small update a few days ago basically removing the s2m function but didnt do much else, im gald it is working now! and yeah the new casino-blackjack is still testing phase
