### ISSUE TITLE
No such export GetCoreObject in resource qb-core

### ISSUE THREAD

**Issue by zulsyazwan** [dojwun/doj-casino#8]
Hi i have this error. how to fix? im new to qb

[ script:qb-blackjack] Error loading script server/server.lua in resource qb-blackjack: citizen:/scripting/lua/scheduler.lua:1155: No such export GetCoreObject in resource qb-core
[ script:qb-blackjack] stack traceback:
[ script:qb-blackjack] 	[C]: in function 'error'
[ script:qb-blackjack] 	citizen:/scripting/lua/scheduler.lua:1155: in metamethod '__index'
[ script:qb-blackjack] 	@qb-blackjack/server/server.lua:1: in main chunk

**Comment by dojwun** [comment]
Update your qb-core

**Comment by zulsyazwan** [comment]
https://github.com/qbcore-framework/qb-core use this one ? or just some portion need to be update?

**Comment by dojwun** [comment]
yes
